on: [push, pull_request]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Verifica o repositório do Git
        uses: actions/checkout@v3

      - name: Instala o node com a versão
        uses:  actions/setup-node@v
        with:
          node-version: 16
      
      - name: Instalando as dependências
        run: npm ci

      - name: Executando o lint para verificar se a erros
        run: npx eslint .