name: Node.js CI

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
        
      - name: Instalando dependências
        run: npm ci
        
      - name: Rodando ESlint
        run: npm run lint
        
      - name: Rodando os tests
        run: npm test
